### ISSUE TITLE
Link to meetup group

### ISSUE THREAD

**Issue by lchski** [CivicTechWR/CivTe.ch-Site#2]
Hi folks! Really happy to see a civic tech meetup group coming to Waterloo Region. Went to the site looking for a link to [the meetup group](https://www.meetup.com/CivicTechWR/), to no avail... I found it through the Twitter feed. Could you add a link to the site? Thanks!

**Comment by KristinaTaylor** [comment]
Updated the page with a link to meetup on the contact page and also cleaned up some broken links in the footer. 

Will figure out a way to get future meetup events sync'd to the google calendar on the events page.
